- name: Include secrets 
  include_vars:
    file: vaults/vault.yaml
    name: vault

- name: Creates curiel_bot data directory
  become: true
  file:
    path: /mnt/storage/curiel_bot
    state: directory

- name: Creates curiel_bot config file
  become: true
  file:
    path: /etc/curiel_bot
    state: directory
    
- name: copy config file
  become: true
  template:
    dest: /etc/curiel_bot/.env
    src: .env.j2
  no_log: true

- name: install curiel bot
  become: true
  community.docker.docker_container:
    name: curiel_bot
    restart: true
    restart_policy: always
    image:   carnivuth/curiel_bot:latest
    volumes:
      - /mnt/storage/curiel_bot:/usr/src/curiel_bot/data
      - /etc/curiel_bot/.env:/usr/src/curiel_bot/.env
