- name: Copy nextcloud compose file
  become: true
  copy:
    src: nextcloud.yaml
    dest: /var/lib/docker-compose-files/

- name: Copy docker secrets
  become: true
  copy:
    src: '{{ item }}'
    dest: /var/lib/docker-compose-files/
  loop: '{{ docker_secrets_files }}'

- name: Start nextcloud container
  become: true
  command: docker-compose  -f /var/lib/docker-compose-files/nextcloud.yaml up -d