- name: Include secrets 
  include_vars:
    file: vaults/vault.yaml
    name: vault
  no_log: true

- name: Copy nextcloud compose file
  become: true
  template:
    src: nextcloud.yaml.j2
    dest: /var/lib/docker-compose-files/nextcloud.yaml

- name: Start nextcloud container
  become: true
  command: docker-compose  -f /var/lib/docker-compose-files/nextcloud.yaml up -d