- name: Install Docker Engine
  become: true
  apt:
    name:
      - docker.io
 
- name: Install docker compose
  become: true
  ansible.builtin.apt:
    name: docker-compose
    state: present
    
- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: '{{ docker_user }}'
    groups: docker
    append: true

- name: reboot machine
  become: true
  reboot:

