- hosts: dns_host
  roles:
    - install_dnsmasq

- hosts: all
  tasks:
  
    - name: Add rotate option
      become: true
      lineinfile:
        path: /etc/resolv.conf
        line: 'option rotate'
        insertbefore: BOF

    - name: Add dns server
      become: true
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ dns_server }}'
        insertbefore: BOF
        
    - name: Add dns search parameter
      become: true
      lineinfile:
        path: /etc/resolv.conf
        regexp: 'search .*'
        line: 'search {{ dns_server }}'
        insertbefore: BOF