- hosts: dns_host
  roles:
    - install_dnsmasq

- hosts: all
  tasks:
    - name: add dns server
      become: true
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ dns_server }}'