- hosts: dns_host
  roles:
    - install_dnsmasq

- hosts: all
  tasks:
  
    - name: Add rotate option
      become: true
      lineinfile:
        path: /etc/resolv.conf
        line: 'option rotate'

    - name: Add dns server
      become: true
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver {{ dns_server }}'
