
- name: Create minecraft user 
  become: true
  user:
    name: minecraft
    home: /usr/local/minecraft
    create_home: true 

- name: Install java
  become: true
  apt:
    name: openjdk-17-jdk
    state: latest
    update_cache: true

- name: Download minecraft jar
  become: true
  get_url:
    url: https://piston-data.mojang.com/v1/objects/5b868151bd02b41319f54c8d4061b8cae84e665c/server.jar
    dest: /usr/local/minecraft/server.jar
    owner: minecraft

- name: Accept eula
  become: true
  lineinfile:
    create: true
    path: /usr/local/minecraft/eula.txt
    line: 'eula=true'
    owner: minecraft

- name: Copy systemd unit file
  become: true
  copy:
    src: minecraft.service
    dest: /etc/systemd/system/minecraft.service

- name: Start server
  become: true
  service:
    name: minecraft
    enabled: true
    state: started



