
- name: Create minecraft user 
  become: true
  user:
    name: minecraft
    home: /usr/local/minecraft
    create_home: true 

- name: Install some script utilities
  become: true
  apt:
    name: 
      - jq
      - tar
      - curl
      - cron
      - mailutils
    state: latest
    update_cache: true

- name: Copy check_updates script
  become: true
  copy:
    src: check_updates.sh
    dest: /usr/local/minecraft/check_updates.sh
    owner: root
    mode: '700'

- name: Copy update script
  become: true
  copy:
    src: update.sh
    dest: /usr/local/minecraft/update.sh
    owner: root
    mode: '700'

- name: Get latest minecraft version
  become: true
  ansible.builtin.shell: >
    curl -s $(curl -s 'https://launchermeta.mojang.com/mc/game/version_manifest.json' | jq -r  '.versions[0].url') | jq -r  '.downloads.server.url'
  args:
    executable: /bin/bash
  register: latest_version_url

- name: Install java
  become: true
  apt:
    name: openjdk-17-jdk
    state: latest
    update_cache: true

- name: Download minecraft jar
  become: true
  get_url:
    url: '{{ latest_version_url }}'
    dest: /usr/local/minecraft/server.jar
    owner: minecraft


- name: Accept eula
  become: true
  lineinfile:
    create: true
    path: /usr/local/minecraft/eula.txt
    line: 'eula=true'
    owner: minecraft

- name: Copy systemd unit file
  become: true
  copy:
    src: minecraft.service
    dest: /etc/systemd/system/minecraft.service

- name: Add cron job to check for updates every 5 minutes
  become: true
  ansible.builtin.cron:
    name: "check for minecraft server updates"
    minute: "*/5"
    user: root
    job: " /usr/local/minecraft/check_updates.sh"
  notify: Restart crond

- name: Start server
  become: true
  service:
    name: minecraft
    enabled: true
    state: started



