LDAP_server:
  hosts: 
    castleterra:
          # ldap server address 
          address: 192.168.0.2
          # ldap organization
          organization: homelab
          # ldap dc
          dc: homelab
          # ldap password
          pwd: pippo  

LDAP_clients:
  hosts:
    castleterra:
    wailhost:
    storax:
  vars:
    #ldap server parameters
    address: 192.168.0.2
    dc: homelab
    pwd: pippo  
    sudo_group: matteo

## MACHINES WITH COCKPIT 
cockpit_hosts:
  hosts:
    wailhost:
    storax:

## MACHINES WITH DOCKER RUNTIME SUPPORT 
docker_hosts:
  hosts:
    wailhost:
    storax:

## MACHINES WITH PORTAINER 
portainer_dashboard_host:
  hosts: 
    wailhost:

portainer_agent_hosts:
  hosts: 
    storax:

# MACHINE WITH HOMER DASHBOARD
dashboard_host:
  hosts:
    wailhost:

# NAS SERVER HOST
nas_server:
  hosts:
    storax:
      # public share folder path
      public_folder_path: /home/shares/public
      # workgroup
      samba_workgroup: homelab
      # force group parameter
      public_group: public
      # samba configuration block name
      public_folder: public
  
all:
  hosts:
    castleterra:
        ansible_user: vagrant
        ansible_ssh_private_key_file: staging/castleterra/.vagrant/machines/default/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2222
        ansible_hostname: castleterra

    storax:
        ansible_user: vagrant
        ansible_ssh_private_key_file: staging/storax/.vagrant/machines/default/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2223
        ansible_hostname: storax

    wailhost:
        ansible_user: vagrant
        ansible_ssh_private_key_file: staging/wailhost/.vagrant/machines/default/virtualbox/private_key
        ansible_host: 127.0.0.1 
        ansible_port: 2224
        ansible_hostname: wailhost
