- name: install packages
  become: true
  apt:
    name:
      - git
      - ansible
    state: latest
    update_cache: true

- name: clone homelab repo
  become: true
  git:
    repo: https://github.com/carnivuth/homelab
    dest: /usr/local/homelab

- name: Add cron job to update repo every 5 minutes
  become: true
  ansible.builtin.cron:
    name: "update homelab repo"
    minute: "*/2"
    user: root
    job: "cd /usr/local/homelab && git pull"
  notify: Restart dnsmasq

- name: Add cron job to update dns every 30 minutes
  become: true
  ansible.builtin.cron:
    name: "update dns"
    minute: "*/30"
    user: root
    job: "cd /usr/local/homelab && ansible-playbook -i /usr/local/homelab/inventory/prod.yaml /usr/local/homelab/dnsmasq.yaml "
  notify: Restart dnsmasq
