- name: Copy sudo ldap schema
  become: true
  copy:
    src: sudo.schema
    dest: /etc/ldap/schema/sudo.schema

- name: Add password for ldap root
  become: true
  blockinfile:
    path: '/etc/ldap/slapd.d/cn=config/olcDatabase={0}config.ldif'
    block: |
       olcRootPW: {{ pwd }}
      
- name: Restart slapd daemon
  become: true
  service:
    name: slapd
    state: restarted

- name: Add ldap schema 
  become: true
  command:
    cmd: ldapadd -H ldap://localhost/ -D "cn=admin,cn=config" -x -w "{{ pwd }}" -f /etc/ldap/schema/sudo.schema
  register: result
  failed_when: 
     - result.rc != 0 
     - "'Duplicate attributeType' not in result.stderr" 
  #no_log: true

- name: Insert ldap People entry
  community.general.ldap_entry:
    dn: ou=People,dc="{{ dc }}"
    objectClass: organizationalunit
    server_uri: ldap://localhost/
    bind_dn: cn=admin,dc="{{ dc }}"
    bind_pw: "{{ pwd }}"
    attributes:
      description: System Users
      ou: People

- name: Insert ldap Groups entry
  community.general.ldap_entry:
    dn: ou=Groups,dc="{{ dc }}"
    objectClass: organizationalunit
    server_uri: ldap://localhost/
    bind_dn: cn=admin,dc="{{ dc }}"
    bind_pw: "{{ pwd }}"
    attributes:
      description: System Groups
      ou: Groups

- name: Insert ldap SUDOers entry
  community.general.ldap_entry:
    dn: ou=SUDOers,ou=People,dc="{{ dc }}"
    objectClass: 
      - top
      - organizationalunit 
    server_uri: ldap://localhost/
    bind_dn: cn=admin,dc="{{ dc }}"
    bind_pw: "{{ pwd }}"
    attributes:
      description: Sudo user 

### LDAP USERS
- name: Insert ldap users
  community.general.ldap_entry:
    dn: uid="{{ item.uid }}",ou=People,dc="{{ dc }}"
    objectClass:
      - top
      - posixAccount
      - shadowAccount
      - inetOrgPerson

    server_uri: ldap://localhost/
    bind_dn: cn=admin,dc="{{ dc }}"
    bind_pw: "{{ pwd }}"
    attributes:
      givenName: "{{ item.givenName }}"
      cn: "{{ item.cn }}"
      sn: "{{ item.sn }}"
      mail: "{{ item.mail }}"
      uid: "{{ item.uid }}"
      uidNumber: "{{ item.uidNumber }}"
      gidNumber: "{{ item.gidNumber }}"
      homeDirectory: "{{ item.homeDirectory }}"
      loginShell: "{{ item.loginShell }}"
      gecos: "{{ item.gecos }}"
      userPassword: "{{ item.userPassword }}"
  loop: "{{ users }}"

### LDAP GROUPS
- name: Insert ldap Groups
  community.general.ldap_entry:
    dn: cn="{{ item.cn }}",ou=Groups,dc="{{ dc }}"
    objectClass:
      - top
      - posixGroup
    server_uri: ldap://localhost/
    bind_dn: cn=admin,dc="{{ dc }}"
    bind_pw: "{{ pwd }}"
    attributes:
      cn: "{{ item.cn }}"
      gidNumber: "{{ item.gidNumber }}"
  loop: "{{ usergroups }}"

