- name: Create jenkins agent
  become: true
  user:
    name: jenkins
    home: /usr/local/jenkins
    create_home: true
    append: true
    
- name : Create ssh folder
  become: true
  file:
    path: /usr/local/jenkins/.ssh
    owner: jenkins
    state: directory

- name : Add jenkins host ssh key
  become: true
  copy:
    dest: /usr/local/jenkins/.ssh/authorized_keys
    src: 'vaults/jenkins_key.pub'

- name: install java 17
  become: true
  apt:
    name: openjdk-17-jdk
    update_cache: true
    state: latest