- name: Update all packages to their latest version
  become: true 
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
    
- name: Install some default packages
  become: true 
  ansible.builtin.apt:
   pkg:
    - vim
