- name: Update all packages to their latest version
  become: true 
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    
- name: Install some default packages
  become: true 
  ansible.builtin.apt:
   pkg:
    - vim
    - sudo
   state: latest

- name: Copy motd file
  become: true 
  ansible.builtin.copy:
   src: '{{ ansible_hostname }}-motd'
   dest: /etc/motd
  ignore_errors: true

- include_tasks: create_admin_user.yaml

- name: Copy default vim configuration
  become: true 
  ansible.builtin.copy:
   src: .vimrc
   dest: '{{ item }}/.vimrc'
  with_items: 
    - /root
    - '{{ admin_home }}'

- name: Copy default bash aliases
  become: true 
  ansible.builtin.copy:
   src: .bash_aliases
   dest: '{{ item }}/.bash_aliases'
  with_items: 
    - /root
    - '{{ admin_home }}'
