- name: Update all packages to their latest version
  become: true 
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
    
- name: Install some default packages
  become: true 
  ansible.builtin.apt:
   pkg:
    - vim
    - sudo
   state: latest

- name: Copy default vim configuration
  become: true 
  ansible.builtin.copy:
   src: .vimrc
   dest: /root/.vimrc

- name: Copy default bash aliases
  become: true 
  ansible.builtin.copy:
   src: .bash_aliases
   dest: /root/.bash_aliases

- name: Copy motd file
  become: true 
  ansible.builtin.copy:
   src: '{{ ansible_hostname }}-motd'
   dest: /etc/motd
  ignore_errors: true

#include_tasks: create_admin_user.yaml
